export default {
  idle: [{
    audio: 'sounds/drums.mp3',
    fadeIn: 0.2,
    fadeOut: 2,
    gain: 0,
    spatialized: false,
  }],
  points: [{
    id: 'strasse',
    name: 'An der Straße',
    latitude: 48.052978,
    longitude: 8.204961,
    audio: 'sounds/harmony.mp3',
    innerRadius: 10,
    outerRadius: 20,
    fadeIn: 0.2,
    fadeOut: 2,
    gain: 0,
    spatialized: false,
  }, {
    id: 'sparkasse',
    name: 'Sparkasse',
    latitude: 48.053292,
    longitude: 8.205072,
    audio: 'sounds/melody.mp3',
    innerRadius: 10,
    outerRadius: 20,
    fadeIn: 0.2,
    fadeOut: 2,
    gain: 0,
    spatialized: false,
  }, ],
};