export default {
  map: {
    'top-right-latitude': 48.049885,
    'top-right-longitude': 8.210522,
    'botton-left-latitude': 48.049885,
    'botton-left-longitude': 8.210522,
    image: 'images/map.png',
  },
  points: [{
    id: 'Punkt 1',
    name: 'Kuli und Blei',
    latitude: 48.049885,
    longitude: 8.210522,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_KuliUndBlei.wav',
    innerRadius: 7,
    outerRadius: Infinity,
    fadeIn: 0.2,
    fadeOut: 2,
    gain: 0,
    spatialized: false,
  }, {
    id: 'Punkt 2',
    name: 'Restdrums',
    latitude: 48.049939,
    longitude: 8.210295,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Restdrums.wav',
    innerRadius: 7,
    outerRadius: Infinity,
    fadeIn: 0.2,
    fadeOut: 2,
    gain: 2,
    spatialized: false,
  }, {
    id: 'Punkt 3',
    name: 'Synths',
    latitude: 48.049925,
    longitude: 8.209992,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Synths.wav',
    innerRadius: 7,
    outerRadius: 23,
    fadeIn: 3,
    fadeOut: 2,
    gain: -18,
    spatialized: false,
  }, {
    id: 'Punkt 4',
    name: 'Piano',
    latitude: 48.049909,
    longitude: 8.209643,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Piano.wav',
    innerRadius: 7,
    outerRadius: 22,
    fadeIn: 2,
    fadeOut: 2,
    gain: -5,
    spatialized: false,
  }, {
    id: 'Punkt 5',
    name: 'Gitarren',
    latitude: 48.049813,
    longitude: 8.209886,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Gitarren.wav',
    innerRadius: 7,
    outerRadius: 17,
    fadeIn: 2,
    fadeOut: 2,
    gain: -14,
    spatialized: false,
  }, {
    id: 'Punkt 6',
    name: 'Boum',
    latitude: 48.049721,
    longitude: 8.210156,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Boum.wav',
    innerRadius: 7,
    outerRadius: 12,
    fadeIn: 2,
    fadeOut: 2,
    gain: 0,
    spatialized: false,
  }, {
    id: 'Punkt 7',
    name: 'Refrain',
    latitude: 48.049804,
    longitude: 8.210344,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Refrain.wav',
    innerRadius: 5,
    outerRadius: 10,
    fadeIn: 0.2,
    fadeOut: 2,
    gain: 0,
    spatialized: false,
  }, {
    id: 'Punkt 8',
    name: 'Gitarren 2',
    latitude: 48.049804,
    longitude: 8.210344,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Gitarren.wav',
    innerRadius: 5,
    outerRadius: 10,
    fadeIn: 0.2,
    fadeOut: 2,
    gain: -14,
    spatialized: false,
  }, {
    id: 'Punkt 9',
    name: 'Synths 2',
    latitude: 48.049804,
    longitude: 8.210344,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Synths.wav',
    innerRadius: 5,
    outerRadius: 10,
    fadeIn: 0.2,
    fadeOut: 2,
    gain: -18,
    spatialized: false,
  }, {
    id: 'Punkt 10',
    name: 'Piano 2',
    latitude: 48.049804,
    longitude: 8.210344,
    audio: 'sounds/Shiva! A walk in the depth of hell_Thema_Piano.wav',
    innerRadius: 5,
    outerRadius: 10,
    fadeIn: 0.2,
    fadeOut: 2,
    gain: -6,
    spatialized: false,
  }, ],
};
